### ISSUE TITLE
Incompatible with Android Gradle plugin v1.5.0

### ISSUE THREAD

**Issue by tobykurien** [xtext/xtend-gradle-plugin#34] opened 2015-11-26 08:08 UTC
If you compile an app with gradle 1.5.0 you get this error:

```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.AppExtension.getApplicationVariants()Lorg/gradle/api/internal/DefaultDomainObjectSet;
        at org.xtend.gradle.XtendAndroidPlugin$1.execute(XtendAndroidPlugin.java:72)
        at org.xtend.gradle.XtendAndroidPlugin$1.execute(XtendAndroidPlugin.java:65)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 46 more
```

**Comment by tobykurien** [comment] 2015-11-26 10:42
This might have some useful information: http://tools.android.com/tech-docs/new-build-system/transform-api

**Comment by oehme** [comment] 2015-12-01 14:39
Looks like a trivial, but incompatible API change.

**Comment by tobykurien** [comment] 2015-12-01 14:42
I am hoping that if this is fixed, it will be compatible with the android gradle plugin v2.0.0-alpha1, which implements the instant run feature.

**Comment by oehme** [comment] 2015-12-01 14:58
Fixed by cff1466a8e90f4c00e5196ff5e60567a24c7546f

**Comment by oehme** [comment] 2015-12-01 14:59
Will be available as 0.4.13 soon.

**Closed by oehme** 2015-12-01 14:58 UTC

**Comment by tobykurien** [comment] 2015-12-02 07:49
I tried 0.4.13 today with android gradle 1.5.0, I still get the above error

**Comment by oehme** [comment] 2015-12-02 09:33
Ah, of course, the return type is part of the signature in the class file. So the only workaround is to recompile against 1.5. 

However, they have the same problem in getLibraryVariants, so I expect them to break us again soon when they find that. *sigh*

**Comment by oehme** [comment] 2015-12-02 09:35
Look for 0.4.14 soon

**Comment by tobykurien** [comment] 2015-12-02 15:24
Great! v0.4.14 is working. It works also with v2.0.0-alpha1 of the android gradle plugin, however the instant run feature does not work :(

**Comment by oehme** [comment] 2015-12-02 16:32
I don't know what instant run does behind the scenes. Do you have some info?

2015-12-02 16:24 GMT+01:00 Toby Kurien <notifications@github.com>:

> Great! v0.4.14 is working. It works also with v2.0.0-alpha1 of the android
> gradle plugin, however the instant run feature does not work :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xtext/xtend-gradle-plugin/issues/34#issuecomment-161331237>
> .
>



-- 
Stefan Oehme
Consultant

Telefon: +49 (0) 431 990 268  70
Mobil:   +49 (0) 151 561 676  77

oehme@itemis.de
https://www.xing.com/profile/Stefan_Oehme4

http://itemis.de
http://twitter.com/itemis


itemis AG
Niederlassung Kiel
Am Germaniahafen 1
24143 Kiel

Rechtlicher Hinweis:

Amtsgericht Dortmund, HRB 20621

Vorstand: Jens Wagener (Vors.), Wolfgang Neuhaus, Dr. Georg Pietrek,
Jens Trompeter, Sebastian Neus

Aufsichtsrat: Prof. Dr. Burkhard Igel (Vors.), Michael Neuhaus, Jennifer
Fiorentino

**Comment by tobykurien** [comment] 2015-12-02 17:20
A lot is happening behind the scenes (proxy classes, socket server, etc.). The best info is in this talk: http://m.youtube.com/?#/watch?v=fs0eira2pRY - watch from 12:50 although the whole talk has lots of info probably relevant to you. This is still alpha though.

My expectation was this: xtend re-generates a modified java file from the xtend file, and AS then picks up the change and everything works as expected.

From my observations, what appears to be happening is that xtend re-generates all the classes, so instant run gives up and closes the app for a re-launch.

Also worth noting is that a change in a resource (e.g. layout file), with no changes made to any xtend files, also doesn't work. It still seems to do a full build.

**Comment by tobykurien** [comment] 2015-12-02 17:28
BTW, this is another talk that might interest you: http://m.youtube.com/watch?v=OOEDKf06WqA (The Android Build System). They mentioned working on API's to allow 3rd party languages (esp Kotlin) to hook into the build system and work with instant run. Most of that (in theory) shouldn't affect Xtend though, since you aren't generating bytecode.

**Comment by oehme** [comment] 2015-12-03 09:37
Thanks for the pointers, I'll have a look.

Indeed, the current incarnation of the Xtend plugin does a full build every
time. However, the generated Java code will be the same, so to the rest of
the tooling it should look like just one Java file changed.

2015-12-02 18:28 GMT+01:00 Toby Kurien <notifications@github.com>:

> BTW, this is another talk that might interest you:
> http://m.youtube.com/watch?v=OOEDKf06WqA (The Android Build System). They
> mentioned working on API's to allow 3rd party languages (esp Kotlin) to
> hook into the build system and work with instant run. Most of that (in
> theory) shouldn't affect Xtend though, since you aren't generating bytecode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xtext/xtend-gradle-plugin/issues/34#issuecomment-161372212>
> .
>



-- 
Stefan Oehme
Consultant

Telefon: +49 (0) 431 990 268  70
Mobil:   +49 (0) 151 561 676  77

oehme@itemis.de
https://www.xing.com/profile/Stefan_Oehme4

http://itemis.de
http://twitter.com/itemis


itemis AG
Niederlassung Kiel
Am Germaniahafen 1
24143 Kiel

Rechtlicher Hinweis:

Amtsgericht Dortmund, HRB 20621

Vorstand: Jens Wagener (Vors.), Wolfgang Neuhaus, Dr. Georg Pietrek,
Jens Trompeter, Sebastian Neus

Aufsichtsrat: Prof. Dr. Burkhard Igel (Vors.), Michael Neuhaus, Jennifer
Fiorentino

**Comment by maannajjar** [comment] 2015-12-04 06:31
Hello @oehme and @tobykurien 

I'm also having the same problem with instant run. It seems like that they're not tracking the sources generated by *registerJavaGeneratingTask*. According to the youtube video, they rely on Android Studio to track code changes to determine which files have changed. 

As a quick workaround, I disabled the xtend gradle plugin and relied on the intellij idea plugin (the facet) to generate the sources. I then added *xtend-gen* folder generated by the idea plugin as java source to the main sourceSets in gradle ( main.java.srcDirs += 'xtend-gen'). A bit hacky, but it worked for me. The intellij plugin is pretty fast and it's been always generating those sources before gradle build process starts.

**Comment by oehme** [comment] 2015-12-04 08:34
Hi Maan,

we cannot use 'registerJavaGeneratingTask', as we need to be guaranteed to
run after all other Java generating tasks (so that for instance the 'R'
class is generated before us). I'll have to dig deeper into the instant run
feature to hopefully find a solution.

Cheers,
Stefan

2015-12-04 7:31 GMT+01:00 Maan Najjar <notifications@github.com>:

> Hello @oehme <https://github.com/oehme> and @tobykurien
> <https://github.com/tobykurien>
>
> I'm also having the same problem with instant run. It seems like that
> they're not tracking the sources generated by *registerJavaGeneratingTask*.
> According to the youtube video, they rely on Android Studio to track code
> changes to determine which files have changed.
>
> As a quick workaround, I disabled the xtend gradle plugin and relied on
> the intellij idea plugin (the facet) to generate the sources. I then added
> *xtend-gen* folder generated by the idea plugin as java source to the
> main sourceSets in gradle ( main.java.srcDirs += 'xtend-gen'). A bit hacky,
> but it worked for me. The intellij plugin is pretty fast and it's been
> always generating those sources before gradle build process starts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xtext/xtend-gradle-plugin/issues/34#issuecomment-161889901>
> .
>



-- 
Stefan Oehme
Consultant

Telefon: +49 (0) 431 990 268  70
Mobil:   +49 (0) 151 561 676  77

oehme@itemis.de
https://www.xing.com/profile/Stefan_Oehme4

http://itemis.de
http://twitter.com/itemis


itemis AG
Niederlassung Kiel
Am Germaniahafen 1
24143 Kiel

Rechtlicher Hinweis:

Amtsgericht Dortmund, HRB 20621

Vorstand: Jens Wagener (Vors.), Wolfgang Neuhaus, Dr. Georg Pietrek,
Jens Trompeter, Sebastian Neus

Aufsichtsrat: Prof. Dr. Burkhard Igel (Vors.), Michael Neuhaus, Jennifer
Fiorentino

**Comment by maannajjar** [comment] 2015-12-04 18:37
Aah ok, that makes sense. Thanks for looking into it!

**Comment by oehme** [comment] 2015-12-10 16:37
I just released 1.0.0-RC1 of the new Xtend Gradle Plugin. Could you guys take it for a spin. I doubt it will fix instantRun, but it should at least give you some faster builds =)

http://xtext.github.io/xtext-gradle-plugin/

**Comment by kuniss** [comment] 2015-12-10 22:38
Runs well with my 3 Xtend projects on Github!
:-)
These are org.xtext.xtend
<http://plugins.gradle.org/plugin/org.xtext.xtend> projects.

Regards, Denis


Am 10.12.2015 um 17:37 schrieb Stefan Oehme:

**Comment by tobykurien** [comment] 2015-12-11 06:05
I've tried it out (on XtendApp), here's some feedback:

- Xtend tests now run! :-)

- Initial compile is indeed much quicker! From about 40 seconds to about 10 seconds! :)

- I get this message in Android Studio: 
```
Source folders generated at incorrect location
Warning:Folder /[snip]/XtendApp/app/build/java/debug
Warning:Folder /[snip]/XtendApp/app/build/java/debugAndroidTest
Information:3rd-party Gradle plug-ins may be the cause
```

- Instant Run doesn't work. This is quite confusing, but when making a change and re-running, it's very slow (takes about 40 seconds). Here's what a normal build looks like:
```
Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
:app:incrementalDebugBuildInfoGenerator
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72310Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2310Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72310Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42310Library UP-TO-DATE
:app:prepareComGithubTobykurienXtendroid0121Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugXtext
WARNING:The import 'org.xtendroid.utils.AlertUtils' is never used. (file:/[snip]/XtendApp/app/src/main/java/com/tobykurien/xtendapp/utils/MyActionBarDrawerToggle.xtend line : 10 column : 1)
:app:injectDebugBootstrap
Instrumented app with a fast deploy bootstrapping application
:app:generateDebugSources
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:fastDeployDebugExtractor UP-TO-DATE
:app:generateDebugInstantRunAppInfo UP-TO-DATE
:app:transformClassesWithInstantRunVerifierForDebug UP-TO-DATE
:app:transformClassesWithInstantRunForDebug UP-TO-DATE
:app:transformClassesWithInstant+restartDexForDebug UP-TO-DATE
:app:transformClasses_enhancedWithInstant+reloadDexForDebug UP-TO-DATE
:app:incrementalDebugSupportDex
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 7.292 secs
```

Now I make a very trivial change in an Xtend file, save and Run. Instant Run doesn't work, instead I get a popup asking:
```
You currently have an active Run session of the same launch configuration.
Do you want to kill that session and proceed with the current launch? [Yes] [No]
```
It does this everytime I try to run (even if no changes are made). If I click No, it aborts the Run. If I click Yes, then it does this long build:
```
Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
:app:incrementalDebugBuildInfoGenerator
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72310Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2310Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72310Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42310Library UP-TO-DATE
:app:prepareComGithubTobykurienXtendroid0121Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
:app:processDebugResources UP-TO-DATE
:app:generateDebugXtext
WARNING:The import 'org.xtendroid.utils.AlertUtils' is never used. (file:/[snip]/XtendApp/app/src/main/java/com/tobykurien/xtendapp/utils/MyActionBarDrawerToggle.xtend line : 10 column : 1)
:app:injectDebugBootstrap
Instrumented app with a fast deploy bootstrapping application
:app:generateDebugSources
:app:compileDebugJavaWithJavac
Note: /[snip]/XtendApp/app/build/generated/source/xtend/debug/com/tobykurien/xtendapp/activity/MainActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:fastDeployDebugExtractor UP-TO-DATE
:app:generateDebugInstantRunAppInfo UP-TO-DATE
:app:transformClassesWithInstantRunVerifierForDebug
:app:transformClassesWithInstantRunForDebug
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentWelcome
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentWelcome
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentTwo
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentTwo
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/utils/Settings
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/utils/Settings
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentOne
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/fragment/FragmentOne
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/utils/Debug
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/utils/Debug
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/utils/MyActionBarDrawerToggle
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/utils/MyActionBarDrawerToggle
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/activity/MainActivity
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/activity/MainActivity
IncrementalSupportVisitor Visiting com/tobykurien/xtendapp/utils/Dependencies
IncrementalChangeVisitor Visiting com/tobykurien/xtendapp/utils/Dependencies
:app:transformClassesWithInstant+restartDexForDebug
:app:transformClasses_enhancedWithInstant+reloadDexForDebug
:app:incrementalDebugSupportDex
:app:transformClassesWithDexForDebug
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 41.725 secs
```
Most of the time is actually spent doing this: ```:app:transformClassesWithDexForDebug```. If the change was in a resource file and not an Xtend class file, then it runs quickly (~ 8 seconds).

I'll keep digging and trying various options and feedback if I find something. I tried setting ```xtend.debugging.sourceInstaller = 'NONE'``` but that made no difference.

**Comment by tobykurien** [comment] 2015-12-11 06:22
BTW, the other issue still exists: if you build XtendApp from scratch (i.e. delete ```build``` and ```app/build``` folders), it fails the first time as it doesn't seem to find the ```Toolbar``` or ```Pager``` classes from the android support library. Subsequent builds work.

**Comment by tobykurien** [comment] 2015-12-11 06:39
Ok, ignore what I said above regarding the popup saying ```You currently have an active Run session...``` and the slow rebuilds and Instant Run not working - seems like the latest update to Android Studio broke it for plain Java projects as well.

**Comment by tobykurien** [comment] 2015-12-11 07:08
Update: after fiddling with the java project (changed android gradle plugin version to alpha1 and then back to alpha2), the java project works fine again. No idea what's going on. I can't get XtendApp to compile quickly after a source change no matter what I try.

**Comment by oehme** [comment] 2015-12-11 08:03
Thanks for the detailed feedback Toby! I fixed the 'folder generated at incorrect location'.

Regarding InstantRun: Can you do sourceInstaller= 'NONE' **and** deactivate the Xtend builder in the IDE? That's of course not a real fix, but I just want to make sure that there is no interference between the Xtend builder in the IDE and the one in Gradle.

Thanks Dennis for verifying it on your projects =)

**Comment by oehme** [comment] 2015-12-11 13:45
Nevermind my last comment, we don't do debug source installation inside IntelliJ, so there is no potential for interference.

Is there a way to run the build on `--info` level to get a better picture of which files were considered OUT-OF-DATE?

**Comment by tobykurien** [comment] 2015-12-12 11:22
Yep, here's the result after making a trivial change (add a character to a string) to an Xtend file in the XtendApp:

http://pasted.co/d13337e2

(It's kind of large so I didn't paste it here)

**Comment by tobykurien** [comment] 2015-12-12 11:27
One thing I noticed in the logs is this, even though I never changes ```AndroidManifest.xml```:

```
Executing task ':app:processDebugManifest' (up-to-date check took 0.002 secs) due to:
  Output file [snip]/XtendApp/app/build/intermediates/manifests/full/debug/AndroidManifest.xml has changed.
All input files are considered out-of-date for incremental task ':app:processDebugManifest'.
```

**Comment by oehme** [comment] 2015-12-12 20:27
The Xtext plugin did a full build because the jar of Xtenddroid changed since the last build. I don't know how that could happen, are the exploded jars postprocessed somehow?

**Comment by oehme** [comment] 2015-12-12 20:29
Also this one looks suspicous:

`  Value of input property 'androidGradlePluginVersion' has changed for task ':app:transformClassesWithInstantRunVerifierForDebug'
`

**Comment by tobykurien** [comment] 2015-12-14 06:46
I didn't change any values, maybe they are being re-written/re-generated by a plugin?

On 12 December 2015 22:29:56 GMT+02:00, Stefan Oehme <notifications@github.com> wrote:
>Also this one looks suspicous:
>
>`  Value of input property 'androidGradlePluginVersion' has changed for
>task ':app:transformClassesWithInstantRunVerifierForDebug'
>`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/xtext/xtend-gradle-plugin/issues/34#issuecomment-164188637

-- 
http://tobykurien.com | @tobykurien

**Comment by oehme** [comment] 2015-12-14 09:56
Can you compare it with a normal incremental build on the command line? Just to make sure that it behaves well there (i.e. only recompiles the MainActivity.xtend)

**Comment by tobykurien** [comment] 2015-12-14 14:20
The behaviour from the command-line is very similar (although it does not do instant run stuff). If I make a simple change, it still takes around 40 seconds to compile. I've pasted the output from the command-line here: http://pasted.co/da8fc6f7

**Comment by tobykurien** [comment] 2015-12-14 14:28
I don't think the slow ```:app:transformClassesWithDexForDebug``` has anything to do with Xtend. Found some info here that I will try: http://stackoverflow.com/questions/34158995/gradle-build-slow-on-transformclasseswithdexfordebug

**Comment by oehme** [comment] 2015-12-14 17:16
The behavior on the command line is very different actually. It does an incremental build as expected.

So there is something going wrong with instant run. Maybe wait for the next alpha version?

**Comment by tobykurien** [comment] 2015-12-14 17:19
Would it help to see a working instant run gradle build from another project?

On 14 December 2015 19:16:45 GMT+02:00, Stefan Oehme <notifications@github.com> wrote:
>The behavior on the command line is very different actually. It does an
>incremental build as expected.
>
>So there is something going wrong with instant run. Maybe wait for the
>next alpha version?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/xtext/xtend-gradle-plugin/issues/34#issuecomment-164499471

-- 
http://tobykurien.com | @tobykurien

**Comment by oehme** [comment] 2015-12-14 17:24
Sure, but I suspect that this:

`Value of input property 'androidGradlePluginVersion' has changed `

is the root cause.

**Comment by tobykurien** [comment] 2015-12-14 18:24
Ok, FWIW, here's a working instant run:

```
Information:Gradle tasks [:app:incrementalDebugSupportDex]
The client will now receive all logging from the daemon (pid: 29144). The daemon log file: /home/toby/.gradle/daemon/2.8/daemon-29144.out.log
Starting 2nd build in daemon [uptime: 1 mins 41.274 secs, performance: 97%, memory: 18% of 954.5 MB]
Executing build with daemon context: DefaultDaemonContext[uid=f1882813-7e05-4e65-b8a7-79552e73e54c,javaHome=/opt/jdk1.8.0_51,daemonRegistryDir=/home/toby/.gradle/daemon,pid=29144,idleTimeout=10800000,daemonOpts=-Xmx1024M,-Dfile.encoding=UTF-8,-Duser.country=ZA,-Duser.language=en,-Duser.variant]
Starting Build
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Settings evaluated using settings file '[snip]/cheesesquare/settings.gradle'.
Projects loaded. Root project using build file '[snip]/cheesesquare/build.gradle'.
Included projects: [root project 'cheesesquare', project ':app']
Evaluating root project 'cheesesquare' using build file '[snip]/cheesesquare/build.gradle'.
Evaluating project ':app' using build file '[snip]/cheesesquare/app/build.gradle'.
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration wearApp
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestWearApp
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testWearApp
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugWearApp
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugWearApp
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseWearApp
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseWearApp
Selected primary task ':app:incrementalDebugSupportDex' from project :app
All projects evaluated.
Tasks to be executed: [task ':app:compileDebugJavaWithJavac', task ':app:transformClassesWithInstantRunVerifierForDebug', task ':app:transformClassesWithInstantRunForDebug', task ':app:transformClassesWithInstant+restartDexForDebug', task ':app:transformClasses_enhancedWithInstant+reloadDexForDebug', task ':app:incrementalDebugSupportDex']
In-memory cache of [snip]/cheesesquare/.gradle/2.8/taskArtifacts/fileHashes.bin: Size{1368}, CacheStats{hitCount=1318, missCount=1368, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of [snip]/cheesesquare/.gradle/2.8/taskArtifacts/outputFileStates.bin: Size{38}, CacheStats{hitCount=4, missCount=37, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of [snip]/cheesesquare/.gradle/2.8/taskArtifacts/fileSnapshots.bin: Size{61}, CacheStats{hitCount=0, missCount=53, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of [snip]/cheesesquare/.gradle/2.8/taskArtifacts/taskArtifacts.bin: Size{27}, CacheStats{hitCount=0, missCount=27, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
:app:compileDebugJavaWithJavac (Thread[Daemon worker Thread 2,5,main]) started.
:app:compileDebugJavaWithJavac
Executing task ':app:compileDebugJavaWithJavac' (up-to-date check took 0.014 secs) due to:
  Input file [snip]/cheesesquare/app/src/main/java/com/support/android/designlibdemo/CheeseDetailActivity.java has changed.
Compiling with JDK Java compiler API.
:app:compileDebugJavaWithJavac (Thread[Daemon worker Thread 2,5,main]) completed. Took 1.791 secs.
:app:transformClassesWithInstantRunVerifierForDebug (Thread[Daemon worker Thread 2,5,main]) started.
:app:transformClassesWithInstantRunVerifierForDebug
Executing task ':app:transformClassesWithInstantRunVerifierForDebug' (up-to-date check took 0.011 secs) due to:
  Input file [snip]/cheesesquare/app/build/intermediates/classes/debug/com/support/android/designlibdemo/CheeseDetailActivity.class has changed.
:app:transformClassesWithInstantRunVerifierForDebug (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.099 secs.
:app:transformClassesWithInstantRunForDebug (Thread[Daemon worker Thread 2,5,main]) started.
:app:transformClassesWithInstantRunForDebug
Executing task ':app:transformClassesWithInstantRunForDebug' (up-to-date check took 0.011 secs) due to:
  Input file [snip]/cheesesquare/app/build/intermediates/classes/debug/com/support/android/designlibdemo/CheeseDetailActivity.class has changed.
IncrementalSupportVisitor Visiting com/support/android/designlibdemo/CheeseDetailActivity
IncrementalChangeVisitor Visiting com/support/android/designlibdemo/CheeseDetailActivity
:app:transformClassesWithInstantRunForDebug (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.166 secs.
:app:transformClassesWithInstant+restartDexForDebug (Thread[Daemon worker Thread 2,5,main]) started.
:app:transformClassesWithInstant+restartDexForDebug
Executing task ':app:transformClassesWithInstant+restartDexForDebug' (up-to-date check took 0.009 secs) due to:
  Input file [snip]/cheesesquare/app/build/intermediates/transforms/instantRun/debug/folders/1/1/main/com/support/android/designlibdemo/CheeseDetailActivity.class has changed.
  Input file [snip]/cheesesquare/app/build/intermediates/transforms/instantRun/debug/folders/4000/1/enhanced/com/support/android/designlibdemo/CheeseDetailActivity$override.class has changed.
:app:transformClassesWithInstant+restartDexForDebug (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.016 secs.
:app:transformClasses_enhancedWithInstant+reloadDexForDebug (Thread[Daemon worker Thread 2,5,main]) started.
:app:transformClasses_enhancedWithInstant+reloadDexForDebug
Executing task ':app:transformClasses_enhancedWithInstant+reloadDexForDebug' (up-to-date check took 0.008 secs) due to:
  Input file [snip]/cheesesquare/app/build/intermediates/transforms/instantRun/debug/folders/1/1/main/com/support/android/designlibdemo/CheeseDetailActivity.class has changed.
  Input file [snip]/cheesesquare/app/build/intermediates/transforms/instantRun/debug/folders/4000/1/enhanced/com/support/android/designlibdemo/CheeseDetailActivity$override.class has changed.
Loading jar into dexer: /opt/android-sdk-linux/build-tools/23.0.2/lib/dx.jar
Dexing [snip]/cheesesquare/app/build/intermediates/reload-dex/debug in-process: 326.5 ms
processing archive [snip]/cheesesquare/app/build/intermediates/reload-dex/debug/classes.jar...
processing com/android/build/gradle/internal/incremental/AppPatchesLoaderImpl.class...
processing com/support/android/designlibdemo/CheeseDetailActivity$override.class...
:app:transformClasses_enhancedWithInstant+reloadDexForDebug (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.422 secs.
:app:incrementalDebugSupportDex (Thread[Daemon worker Thread 2,5,main]) started.
:app:incrementalDebugSupportDex
Executing task ':app:incrementalDebugSupportDex' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:incrementalDebugSupportDex (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.003 secs.
Information:BUILD SUCCESSFUL
Information:Total time: 3.606 secs
Stopped 0 compiler daemon(s).
Information:0 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by oehme** [comment] 2015-12-14 18:55
I tried doing it on my Windows machine, but Android Studio 2.0 Alpha doesn't even start. I'll give it a try on a Mac later.

**Comment by oehme** [comment] 2015-12-15 08:52
My command line with Xtend looks just as fast as your simple Java app. Couldn't try with AS yet.

**Comment by tobykurien** [comment] 2016-02-17 07:13
FYI: Updating to android gradle plugin v2.0.0-beta5 and using Android Studio 2 beta5 -> Instant Run now works with Xtend! :-)

**Comment by oehme** [comment] 2016-02-17 11:57
Awesome :)
Am 17.02.2016 2:13 Vorm. schrieb "Toby Kurien" notifications@github.com:
