### ISSUE TITLE
Xtend-based tests are not run in Android Studio or Gradle

### ISSUE THREAD

**Issue by tobykurien** [xtext/xtend-gradle-plugin#35] opened 2015-11-26 11:33 UTC
It seems xtend-based tests are not picked up by Gradle or Android-studio.To reproduce, check out the XtendApp project: http://github.com/tobykurien/xtendapp

In the root folder, run: ```gradle connectedAndroidTest --info```

You will see that it runs 3 tests:

```
Starting 3 tests on MB526 - 4.4.4

com.tobykurien.xtendapp.ApplicationTest > testApplicationTestCaseSetUpProperly[MB526 - 4.4.4] SUCCESS 

com.tobykurien.xtendapp.ApplicationTest > testAndroidTestCaseSetupProperly[MB526 - 4.4.4] SUCCESS 

com.tobykurien.xtendapp.JavaTest > testMe[MB526 - 4.4.4] SUCCESS 
```
It does not pick up the test in the ```BasicUiTest.xtend``` file, which is almost identical to the ```JavaTest```, except in Xtend. Perhaps this is because the Xtend compilation is not being triggered at the right time? Let me know if you need more info.

**Comment by oehme** [comment] 2015-12-01 14:38
Yes, the plugin does not yet handle tests. We will fix that with the next version

**Comment by oehme** [comment] 2015-12-01 15:48
Closing as duplicate of #31

**Closed by oehme** 2015-12-01 15:48 UTC
